### ISSUE TITLE
it only shows the last 4 table values.

### ISSUE THREAD

**Issue by WK-GiHu** [nothing63/scraper#1]
@nothing63 

>it only shows the last 4 table values.

The line 17 is the `Row` and line 18 is the `Column`

https://github.com/nothing63/sraper/blob/4b4c3c05ca907b9c28c7ab9d523dc2158e54fb63/grid.py#L17

You have one `for ...` loop to much?

**Comment by nothing63** [comment]
Now it displays correctly, I had one loop too many. Unfortunately, I still don't understand how I should do it to display the layout I drew and showed in SO. I try it:
```python
from tkinter import *
from bs4 import BeautifulSoup
import requests
root=Tk()
root.grid_columnconfigure(0, weight=1)
root.grid_rowconfigure(0, weight=1)
keyboard=Frame(root,padx=5,pady=5,bg="red")
keyboard.grid(row=0,column=0, sticky=NSEW)

url = 'https://www.nbp.pl/home.aspx?f=/kursy/kursyc.html'
 
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)
 
soup = BeautifulSoup(response.text, 'lxml')
for s in soup.find_all('table', attrs={'class' : 'pad5'}):
    for row, row_buttons in enumerate(s.find_all('td')):
        keyboard.grid_rowconfigure(row, weight=1)
        for col, text in enumerate(row_buttons):
            keyboard.grid_columnconfigure(col, weight=1)
            row = row + 1
            Button(keyboard, padx=5, pady=5, text=text).grid(row=row, column=col, sticky='EWNS')
            Button(keyboard, padx=5, pady=5, text=text).grid(row=row, column=col, sticky='EWNS')
            Button(keyboard, padx=5, pady=5, text=text).grid(row=row, column=col, sticky='EWNS')
            Button(keyboard, padx=5, pady=5, text=text).grid(row=row, column=col, sticky='EWNS')

root.mainloop()
``` What should it look like?

**Comment by WK-GiHu** [comment]
@nothing63 

Please don't past the whole code into comment, updat your file instead.
It's simpler to review and I need also the Line number and history.

Instead of showing your allready known `A B C ...` grid show a screenshoot what you acually get.

**Comment by nothing63** [comment]
![Screenshot from 2020-03-07 22-37-10](https://user-images.githubusercontent.com/36797326/76152828-89348b00-60c4-11ea-9c72-69eeae0d462a.png)
^ this is how it looks. I want it to look like this:
![fsfg](https://user-images.githubusercontent.com/36797326/76152837-a5d0c300-60c4-11ea-917f-10303f575756.png)

**Comment by WK-GiHu** [comment]
@nothing63 

Look like `row` is still wrong

### Update your `grid.py` so i can review

**Comment by nothing63** [comment]
https://github.com/nothing63/scraper/blob/master/grid.py I am updated, how can I do it to work?

**Comment by WK-GiHu** [comment]
@nothing63 

Change in line 17 to `for row, tr in enumerate(table.find_all('tr')):`
https://github.com/nothing63/scraper/blob/3473c5fb96a17bd2edee121f5ab84b361996b2b0/grid.py#L17

Change in line 19 to `for col, td in enumerate(tr.find_all('td')):`
https://github.com/nothing63/scraper/blob/3473c5fb96a17bd2edee121f5ab84b361996b2b0/grid.py#L19

Remove line 21
https://github.com/nothing63/scraper/blob/3473c5fb96a17bd2edee121f5ab84b361996b2b0/grid.py#L21

Remove line 23, 23, 25
https://github.com/nothing63/scraper/blob/3473c5fb96a17bd2edee121f5ab84b361996b2b0/grid.py#L23

**Comment by nothing63** [comment]
https://github.com/nothing63/scraper/blob/master/grid.py
The layout is good, but for what reason does it look like image?
![Screenshot from 2020-03-07 23-02-03](https://user-images.githubusercontent.com/36797326/76153106-ad459b80-60c7-11ea-9e82-e57ec3465ded.png)

**Comment by nothing63** [comment]
By the way, can I ask you where did you get this knowledge? I can't understand the number of loops and text formatting and many other things. I would like to find a good source of knowledge so that I can learn and broaden my knowledge, do you know any?

**Comment by WK-GiHu** [comment]
@nothing63 

>The layout is good, but for what reason does it look like image?

You have adapted the `Button` example.
Simple replace with `Label` and add `anchor='ne', justify='LEFT'`

**Comment by WK-GiHu** [comment]
@nothing63 

>By the way, can I ask you where did you get this knowledge? 

40 Years coding, reading, reading and reading

>I can't understand the number of loops and text formatting and many other things. I would like to find a good source of knowledge so that I can learn and broaden my knowledge, do you know any?

Do you refer to:

- [ ]  Python
- [ ] tkinter
- [ ] BeautifulSoup

**Comment by nothing63** [comment]
Python but I will gladly learn other things.

**Comment by nothing63** [comment]
> 40 Years coding, reading, reading and reading
I admire, you have to know a lot. I'm starting

**Comment by nothing63** [comment]
> You have adapted the Button example.
Simple replace with Label and add anchor='ne', justify='LEFT'

This unfortunately does not want to work and the effect is the same
https://github.com/nothing63/scraper/blob/master/grid.py#L21

**Comment by WK-GiHu** [comment]
@nothing63 

Change in line 21 to ` text=td.text`
https://github.com/nothing63/scraper/blob/548c5263f4323d972f040ba6e4118ec37b7802b5/grid.py#L21

---

My main Knowledge base:

- [x]  Python
  [Python - Object Oriented](https://www.tutorialspoint.com/python/python_classes_objects.htm)
  [Python3 - Tutorial](https://docs.python.org/3/tutorial/index.html)
  [Python3 - Documentation](https://docs.python.org/3/genindex.html)

- [x] tkinter
  Stackoverflow
  [Tkinterbook](http://effbot.org/tkinterbook/#b)

- [x] BeautifulSoup
  Stackoverflow
  [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#)

**Comment by WK-GiHu** [comment]
@nothing63 

>This unfortunately does not want to work and the effect is the same

One typo, should read: `anchor='nw'`

Works for me, explain the meaning of **does not want to work**

**Comment by nothing63** [comment]
>Change in line 21 to text=td.text

It works, you don't even know how happy I am that it works. Thank you so much for your help, willingness to help and your time. Now it will adapt colors to my application (:

**Comment by WK-GiHu** [comment]
@nothing63 

>It works,

OK, by

**Comment by nothing63** [comment]
Thank you for all!

**Comment by nothing63** [comment]
I have one question, I'm new to SO. I should publish a solution to the problem, whether the solution to the problem may be this issues or should I paste the code in the solution or delete my question on SO?

**Comment by WK-GiHu** [comment]
@nothing63 

> should I paste the code in the solution 

Feel free to do so

>or delete my question on SO?

From my point of view, yes delete it.
Why?
1. Your title describes what you want to do and not the technical problem
  Read [how-to-ask](https://stackoverflow.com/help/how-to-ask)
2. Your example code show a couple problems.
  A good question focus to only **one** issue and makes sure it has not asked before.
3. The basics, 
   - `scrap HTML <Table>`
   - `grid/tabular display in tkinter using Label's` 
  are asked and answered multiple times.

**Comment by nothing63** [comment]
Ok, I will delete my question. Thank you.
